# Generated by Django 6.0.7 on 2026-07-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('last_visit_time', models.DateTimeField(auto_now=True)),
                ('today_views_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-last_visit_time'],
                'unique_together': {('client_id', 'visit_date')},
            },
        ),
    ]
